# Generated by Django 4.1.7 on 2023-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name_30')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='title_90')),
                ('body', models.TextField(blank=True, max_length=100, verbose_name='body')),
                ('data_published', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tagspost')),
            ],
        ),
    ]
