# Generated by Django 4.1.7 on 2023-06-10 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=100, verbose_name='Тело/body/Тіло'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_published',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата публикации/body/Дата публікації (Day.Month.Year)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название/Name/Назва'),
        ),
    ]
