# Generated by Django 4.1.7 on 2023-06-12 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body_alter_post_data_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_main',
            field=models.ImageField(blank=True, max_length=500, upload_to='Posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_published',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
