# Generated by Django 4.1.7 on 2023-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_main',
            field=models.ImageField(blank=True, max_length=500, upload_to='posts/'),
        ),
    ]
