# Generated by Django 4.1.7 on 2023-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_contentbodytranslation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbodytranslation',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
