# Generated by Django 4.1.7 on 2023-03-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contentbodytranslation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentbodytranslation',
            old_name='data',
            new_name='data_json',
        ),
    ]
