# Generated by Django 4.1.7 on 2023-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_gradeeducation_gradeeducationtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtranslation',
            name='specialty',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
