# Generated by Django 4.1.7 on 2023-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_educationtranslation_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtranslation',
            name='specialty',
            field=models.CharField(max_length=90),
        ),
    ]
