# Generated by Django 4.1.7 on 2023-03-19 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_educationtranslation_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeeducationtranslation',
            name='amount',
            field=models.CharField(default=1, max_length=90, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gradeeducationtranslation',
            name='type',
            field=models.CharField(choices=[('B', 'Base'), ('PT', 'Practical training'), ('C', 'Certification')], max_length=90),
        ),
    ]
