# Generated by Django 4.1.7 on 2023-03-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_gradeeducationtranslation_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeeducationtranslation',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
