# Generated by Django 4.1.7 on 2023-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_gradeeducationtranslation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeeducation',
            name='foo_field',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
