# Generated by Django 4.1.7 on 2023-03-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_gradeeducation_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulevonetranslation',
            name='menu_two',
        ),
        migrations.AddField(
            model_name='menulevone',
            name='menu_two',
            field=models.ManyToManyField(blank=True, to='base.menulevtwo'),
        ),
    ]
