# Generated by Django 4.1.7 on 2023-03-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_menulevonetranslation_menu_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetranslation',
            name='menu_one',
        ),
    ]
