# Generated by Django 4.1.7 on 2023-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_basetranslation_menu_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='menu_one',
            field=models.ManyToManyField(blank=True, to='base.menulevone'),
        ),
    ]
