# Generated by Django 4.1.7 on 2023-03-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_base_menu_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationtranslation',
            name='learn_end',
        ),
        migrations.RemoveField(
            model_name='educationtranslation',
            name='learn_start',
        ),
    ]
