# Generated by Django 4.1.7 on 2023-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_educationtranslation_learn_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='learn_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='learn_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
