# Generated by Django 4.1.7 on 2023-03-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_education_learn_end_education_learn_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-translations', '-learn_start', '-learn_end')},
        ),
    ]
