# Generated by Django 4.1.7 on 2023-03-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_gradeeducation_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
    ]
