# Generated by Django 4.1.7 on 2023-03-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_education_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('translations__name', 'learn_start', 'learn_end')},
        ),
    ]
