# Generated by Django 4.1.7 on 2023-03-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_education_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtranslation',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
