# Generated by Django 4.1.7 on 2023-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_educationtranslation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='learn_end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='learn_start',
        ),
        migrations.AddField(
            model_name='education',
            name='max_amount',
            field=models.IntegerField(default=100),
        ),
    ]
