# Generated by Django 4.1.7 on 2023-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_education_learn_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='learn_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='learn_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='url_to_photo_diploma',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
