# Generated by Django 4.1.7 on 2023-03-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_education_learn_end_education_learn_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('learn_end',)},
        ),
    ]
