# Generated by Django 4.1.7 on 2023-03-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_gradeeducation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeeducation',
            options={},
        ),
    ]
