# Generated by Django 4.1.7 on 2023-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_gradeeducation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtranslation',
            name='name_diploma_project',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
