# Generated by Django 4.1.7 on 2023-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_educationtranslation_name_diploma_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Grade_diploma_project',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
