# Generated by Django 4.1.7 on 2023-04-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_education_grade_diploma_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Grade_diploma_project',
            new_name='grade_diploma_project',
        ),
    ]
