# Generated by Django 4.1.7 on 2023-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_skill_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, height_field='100', upload_to='skills/', width_field='100'),
        ),
    ]
