# Generated by Django 4.1.7 on 2023-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_skill_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltranslation',
            name='commentary',
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
    ]
