# Generated by Django 4.1.7 on 2023-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_skilltranslation_commentary_alter_skill_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, choices=[('Base', 'Base'), ('Framework and libs', 'Framework and libs'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50),
        ),
    ]
