# Generated by Django 4.1.7 on 2023-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, max_length=500, upload_to='skills/'),
        ),
    ]
