# Generated by Django 4.1.7 on 2023-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_skill_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, choices=[('Base', 'Base'), ('Framework and libs', 'Framework and libs'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50, verbose_name="person's first name"),
        ),
    ]
