# Generated by Django 4.1.7 on 2023-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_skill_type_alter_skilltranslation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(blank=True, choices=[('Base', 'Base'), ('Frameworks and libs', 'Frameworks and libs'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50, verbose_name='type_50'),
        ),
    ]
