# Generated by Django 4.1.7 on 2023-05-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
    ]
