# Generated by Django 4.1.7 on 2023-05-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_author_tagspost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
