# Generated by Django 4.1.7 on 2023-05-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='TagsPost',
        ),
    ]
