# Generated by Django 4.1.7 on 2023-07-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_sending_emails', '0003_delete_emailend'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
