# Generated by Django 4.1.7 on 2023-07-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_sending_emails', '0005_emailrecipient_user_alter_emailrecipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
