# Generated by Django 4.1.7 on 2023-07-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_sending_emails', '0007_emailtemplate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailrecipient',
            old_name='user',
            new_name='user_owner',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='user',
            new_name='user_owner',
        ),
    ]
