# Generated by Django 4.1.7 on 2023-07-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1_sending_emails', '0010_rename_emailuser_messageemail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messageemailtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messageemailtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MessageEmail',
        ),
        migrations.DeleteModel(
            name='MessageEmailTranslation',
        ),
    ]
